### ISSUE TITLE
Handle subnormal ULPs correctly

### ISSUE THREAD

**Issue by dgrnbrg** [huonw/ieee754#5]
I think that the library doesn't handle subnormal ULPs correctly--here's the JVM implementation, which may be worth imitating on the subnormal case: http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/sun/misc/FpUtils.java#1102

**Comment by huonw** [comment]
I couldn't identify any issues here, but I agree that the handling was definitely not very obvious, so (a year and a half later) I've tested it better and simplified it. Thanks for filing an issue.
